///////////////////////////////////////////////////////////
//  Employed.cs
//  Implementation of the Class Employed
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2021 6:31:33 PM
//  Original author: hamar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SDA.Models;

public class Customer : Prototype{

	

	public Customer(){

	}

	~Customer(){

	}

    public override String works()
    {
       return "Does now work here";
    }
}//end Employed