///////////////////////////////////////////////////////////
//  Employed.cs
//  Implementation of the Class Employed
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2021 6:31:33 PM
//  Original author: hamar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SDA.Models;

public class Employed : Prototype{

	private int age;
	
	public int Age{ 
		set { age = value; }
		get { return age; } 
	}
	private string name;
	public string Name
	{
		set { name = value; }
		get { return name; }
	}
	private string pnumber;
	public string Pnumber
    {
		set { pnumber = value; }
		get{ return pnumber; }
    }
	public override string works() => "Works here";
	public Employed(){

	}

	~Employed(){

	}

    
}//end Employed