///////////////////////////////////////////////////////////
//  Person.cs
//  Implementation of the Class Person
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2021 6:31:37 PM
//  Original author: hamar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public  class Person {

	private int id;
	public int Id
    {
		get { return id; }
		set { id = value; }
    }

	public Person(){

	}

	

	~Person(){

	}

}//end Person