///////////////////////////////////////////////////////////
//  Staff.cs
//  Implementation of the Class Staff
//  Generated by Enterprise Architect
//  Created on:      29-Dec-2021 6:31:39 PM
//  Original author: hamar
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using SDA.DAL;

public class Staff : Employed{

	public Staff(){

	}

	~Staff(){

	}

	public String addMedicine(String mName,double price, int quantity, String description, int id){
		StockDAL s = new StockDAL();
		Stock stock = new Stock();
		stock.name = mName;
		stock.price = price;
		stock.quantity = quantity;	
		stock.description = description;
		stock.id = id;
		

		String stat = s.Add(stock);
		return stat;
	}

	public String Login(String email, String password){
		LoginDAL l = new LoginDAL();
		Staff staff = l.Login(email, int.Parse(password));

		if (staff== null)
		{
			return "incorrect username or password";
		}

		else
		{
			
			Name = staff.Name;
			Age = staff.Age;
			Id = staff.Id;
			Pnumber = staff.Pnumber;
			return "Correct";
			
		}
	}

	public void Logout(){

	}

	public Stock sellmedicine(String mName){
		StockDAL s = new StockDAL();
		Stock stock = s.getMedicine(mName);

		if(stock == null)
        {
			return null;
        }
		else
		return stock;
	}

}//end Staff